<body>
    <div class="container border  mt-5 auto">
        <div class="d-flex ">
            <div class=" p-3">
                home
            </div>
            
            <input class="w-100 rounded-pill" type="text" value="sesarch">
            <a href="#" class="btn btn-danger rounded-pill ml-3">Search</a>
            <div class="p-3">
                signin
            </div>
            <div class="p-3">
                signout
            </div>
        </div>


    </div>
    <div class="border">
        bgrjegoke

    </div>
    <div class="d-flex ">
        <div class="p-2 w-100 border ">Flex item</div>
        <div class="p-2  border ">Flex item</div>
    </div>
</body>